pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        // stage('Test') {
        //     steps {
        //         echo 'Jenkins pipeline is working!'
        //     }
        // }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B clean package'
            }
        }
    }
}
