pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        // stage('Test') {
        //     steps {
        //         echo 'Jenkins pipeline is working!'
        //     }
        // }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('api') {
                    sh 'mvn -B clean package'
                }
                // sh 'mvn -B clean package'
            }
        }
        stage('Unit Tests') {
            steps {
                dir('api') {
                    sh 'mvn -B test'
                }
            }
        }
        stage('Integration Tests') {
            steps {
                dir('api') {
                    sh 'bash integration-test.sh'
                }
            }
        }
    }
    post {
        always {
            junit 'api/target/surefire-reports/*.xml'
        }
    }
}

//Testing my push
